Algoritmo "Pessoa"


Var

nome      :real
endereco  :real
bairro    :real
cidade    :real
estado    :real
fone      :real

Inicio

escreva("Digite seu nome: ")
leia(nome)
escreva("Digite seu endereço: ")
leia(endereco)
escreva("Digite seu bairro: ")
leia(bairro)
escreva("Digite sua cidade: ")
leia(cidade)
escreva("Digite seu estado: ")
leia(estado)
escreva("Digite seu fone: ")
leia(fone)

Fimalgoritmo