Algoritmo "semnome"
 //Objetivo do programa, receber um valor e julgar
 //se ele é positivo ou negativo


Var

valor :inteiro


Inicio
//Citação do valor e execução do que foi pedido.

escreva("Digite um valor: ")
leia(valor)

se(valor = 0) entao
escreva("Valor citado é nulo")
fimse

se(valor < 0) entao
escreva("Valor citado é negativo")
fimse

se(valor > 0) entao
escreva("Valor citado é positivo")
fimse


Fimalgoritmo