Algoritmo "semnome"


Var

a,b:inteiro
c:inteiro

Inicio

escreval("Este programa irá somar se os valores forem iguais, caso não sejam")
escreval("os mesmos serão multiplicados e expostos")
escreval("----------------------------------------------------")

escreva("Digite um valor para A:")
leia(a)
escreva("Digite um valor para B:")
leia(b)


se(a = b) entao
c:=a+b
escreva("Resultado:",c)
senao
c:=a*b
escreva("Resultado:",c)
fimse




Fimalgoritmo